### ISSUE TITLE
Missing promise rejections.

### ISSUE THREAD

**Issue by psmitty7373** [shaozi/ldap-authentication#13]
Need additional promise rejections for:

Error: connect EHOSTUNREACH
Error: getaddrinfo ENOTFOUND

In the event the ldap is outright down or unresolvable.

**Comment by shaozi** [comment]
By default, connection timeout is 5 seconds. You can change that with `connectTimeout` option. When server is not reachable or not found, bind will be rejected.

Please elaborate more what else do you expect?

**Comment by Zerowalker** [comment]
It doesn't seem to be catchable, so when it timeouts it's unhandled, in my cases it causes the server that uses it to crash.

**Comment by psmitty7373** [comment]
As @Zerowalker said, the errors are unhandled, and will simply crash the instance.

**Comment by shaozi** [comment]
hmm... When a server is unreachable, or it is reachable but does not have ldap enabled, the library call will be rejected. You need a try and catch to catch that error. See the last test case in test:

```javascript
try {
  await authenticate(options)
} catch (error) {
  e = error
}
```

The library will not know ahead how to handle such errors. The best it can do is to reject the error. Which means it will crash the instance. You will need to provide logic to catch the crash and handle it (retry after a few seconds, for example, though if a server is not reachable, it may not help) in you own code.

**Comment by shaozi** [comment]
This is probably fixed by merge https://github.com/shaozi/ldap-authentication/pull/19

**Comment by jorgeferhn** [comment]
It isn't fixed in the merge, tried it, but adding the next code found at https://github.com/ldapjs/node-ldapjs/issues/486#issuecomment-434542761 fixes this issue by inserting the events in index.js in the _ldapBind function. Just add the extra event listeners for 'timeout', 'connectTimeout' and 'error' as ldapjs emits them if one of these events happens. Worked for me.
```
client.on('timeout', (err) => {
      reject(err);
 });

client.on('connectTimeout', (err) => {
      reject(err);
});

client.on('error', (err) => {
      reject(err);
});
```

![2021-03-17 (2)](https://user-images.githubusercontent.com/66940054/111573941-1d720d00-8771-11eb-93a2-db2478e57274.png)
![2021-03-17 (3)](https://user-images.githubusercontent.com/66940054/111573973-32e73700-8771-11eb-81e5-9c1f5eef4116.png)

**Comment by shaozi** [comment]
Looks reasonably right! Do you want to create a pull request?

**Comment by jorgeferhn** [comment]
Sure, it's done. Awaiting merge.

**Comment by shaozi** [comment]
Thanks! Merged!
